
---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  labels:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/component: loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
  selector:
    app.kubernetes.io/name: caddy


---
apiVersion: v1
kind: Service
metadata:
  name: cms
  labels:
    app.kubernetes.io/name: cms
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: cms


---
apiVersion: v1
kind: Service
metadata:
  name: lms
  labels:
    app.kubernetes.io/name: lms
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: lms


---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app.kubernetes.io/name: elasticsearch
spec:
  type: ClusterIP
  ports:
    - port: 9200
      protocol: TCP
  selector:
    app.kubernetes.io/name: elasticsearch


---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/name: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app.kubernetes.io/name: mongodb


---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app.kubernetes.io/name: mysql


---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: redis


---
apiVersion: v1
kind: Service
metadata:
  name: smtp
  labels:
    app.kubernetes.io/name: smtp
spec:
  type: ClusterIP
  ports:
    - port: 8025
      protocol: TCP
  selector:
    app.kubernetes.io/name: smtp

---
apiVersion: v1
kind: Service
metadata:
  name: mfe
spec:
  type: NodePort
  ports:
    - port: 8002
      protocol: TCP
  selector:
    app.kubernetes.io/name: mfe