tutor_config_version: "main"

tutor_prod_host_config:
  LMS_HOST: community.abzt.de
  PREVIEW_LMS_HOST: preview.community.abzt.de
  CMS_HOST: studio.community.abzt.de
  MFE_HOST: apps.community.abzt.de

tutor_post_hooks:
  - "{{ tutor_venv_path }}/{{ tutor_exec_name }} plugins enable minio"
  - "{{ tutor_venv_path }}/{{ tutor_exec_name }} plugins enable forum"
  - "{{ tutor_venv_path }}/{{ tutor_exec_name }} plugins enable cairn"
  - "{{ tutor_venv_path }}/{{ tutor_exec_name }} plugins disable home-mfe"
  - "{{ tutor_venv_path }}/{{ tutor_exec_name }} plugins disable course-about-mfe"
  - "{{ tutor_venv_path }}/{{ tutor_exec_name }} plugins enable home-mfe-production"
  - "{{ tutor_venv_path }}/{{ tutor_exec_name }} plugins enable course-about-mfe-production"
  - "{{ tutor_venv_path }}/{{ tutor_exec_name }} plugins enable caddy_proxy"
  - "{{ tutor_venv_path }}/{{ tutor_exec_name }} plugins enable codejail"
  - "{{ tutor_venv_path }}/{{ tutor_exec_name }} plugins enable wordpress-production"
  - "{{ tutor_venv_path }}/{{ tutor_exec_name }} plugins enable discovery"
  - "{{ tutor_venv_path }}/{{ tutor_exec_name }} config save"


