SITE_NAME: "local.overhang.io"
BOOK_URL: ""
LOG_DIR: "/openedx/data/logs"
LOGGING_ENV: "sandbox"
OAUTH_OIDC_ISSUER: "http://local.overhang.io/oauth2"
PLATFORM_NAME: "Community Theme"
FEATURES:
  
  
  CERTIFICATES_HTML_VIEW: true
  PREVIEW_LMS_BASE: "preview.local.overhang.io"
  ENABLE_COURSE_DISCOVERY: true
  ENABLE_COURSEWARE_SEARCH: true
  ENABLE_CSMH_EXTENDED: false
  ENABLE_DASHBOARD_SEARCH:  true
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
  ENABLE_GRADE_DOWNLOADS: true
  ENABLE_LEARNER_RECORDS: false
  ENABLE_MOBILE_REST_API: true
  ENABLE_OAUTH2_PROVIDER: true
  ENABLE_PREREQUISITE_COURSES: true
  ENABLE_THIRD_PARTY_AUTH: true
  MILESTONES_APP: true
LMS_ROOT_URL: "http://local.overhang.io"
CMS_ROOT_URL: "http://studio.local.overhang.io"
CMS_BASE: "studio.local.overhang.io"
LMS_BASE: "local.overhang.io"
CONTACT_EMAIL: "contact@local.overhang.io"
CELERY_BROKER_TRANSPORT: "redis"
CELERY_BROKER_HOSTNAME: "redis:6379"
CELERY_BROKER_VHOST: "0"
CELERY_BROKER_USER: ""
CELERY_BROKER_PASSWORD: ""
ALTERNATE_WORKER_QUEUES: "cms"
ENABLE_COMPREHENSIVE_THEMING: true
COMPREHENSIVE_THEME_DIRS: ["/openedx/themes"]
STATIC_ROOT_BASE: "/openedx/staticfiles"
EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST: "smtp"
EMAIL_PORT: 8025
EMAIL_USE_TLS: false
ACE_ROUTING_KEY: "edx.lms.core.default"
HTTPS: "off"
LANGUAGE_CODE: "en"
SESSION_COOKIE_DOMAIN: "local.overhang.io"

SECRET_KEY: "eHqeglW5j7T68yYtr3yL6XPz"
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
DOC_STORE_CONFIG: null

XQUEUE_INTERFACE:
  django_auth: null
  url: null
DATABASES:
  default:
    ENGINE: "django.db.backends.mysql"
    HOST: "mysql"
    PORT: 3306
    NAME: "openedx"
    USER: "openedx"
    PASSWORD: "2waV0m9w"
    ATOMIC_REQUESTS: true
    OPTIONS:
      init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
EMAIL_HOST_USER: ""
EMAIL_HOST_PASSWORD: ""