name: Build and deploy tutor
on:
  push:
    branches: [ "community-theme" ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: trigger community-tutor workflow
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.ORG_ACCESS_TOKEN }}" \
          https://api.github.com/repos/Abstract-Tech/community-theme-tutor/actions/workflows/tutor.yml/dispatches -d '{"ref":"main", "inputs":{"skip_build_openedx_job":"true"}}'