name: Sync with private repo

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sync to GitLab
        run: |
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          eval $(ssh-agent -s)
          echo "${{ secrets.GITLAB_KNOWN_HOSTS }}" > ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
          echo "${{ secrets.COMMUNITY_THEME_SSH_PRIVATE_KEY }}" | ssh-add -
          git remote add gitlab git@gitlab.com:abstract-germany/community-theme/community-theme-tutor.git
          git push gitlab $GITHUB_REF
