name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_BUILDX: "1"
  SERVER_IP: babilonia.abzt.de
  TUTOR_ROOT: ${{ github.repository }}
  TUTOR_PLUGINS_ROOT: $TUTOR_ROOT/plugins

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Generate tutor env
        run:  tutor config save

      - name: Build tutor openedx image
        run: tutor images build openedx --build-arg BUILDKIT_INLINE_CACHE=1 --docker-arg="--cache-from" --docker-arg="$(tutor config printvalue DOCKER_IMAGE_OPENEDX)"

      - name: Build tutor MFE image
        run: tutor images build openedx --build-arg BUILDKIT_INLINE_CACHE=1 --docker-arg="--cache-from" --docker-arg="$(tutor config printvalue MFE_DOCKER_IMAGE)"

      - name: Push tutor images
        run: |
          docker login -u abstract2tech -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          tutor images push openedx
          tutor images push mfe

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Add SSH key to agent
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          eval $(ssh-agent)
          if [ ! -d ~/.ssh ]; then
            mkdir -p ~/.ssh && chmod 700 ~/.ssh
          fi
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add  ~/.ssh/id_rsa
          ssh-keyscan babilonia.abzt.de > ~/.ssh/known_hosts
          pip install ansible==7.2.0
          ansible-galaxy install -r requirements.yml -p ansible/roles/
          cd $GITHUB_WORKSPACE/ansible
          echo "$ANSIBLE_VAULT_PASSWORD" > vault_pass
          chmod 600 vault_pass
          ansible-playbook --vault-password-file ./vault_pass -u tutor -i inventory.ini -l babilonia.abzt.de --tags tutor_deploy tutor.yml

