name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_BUILDX: "1"
  SERVER_IP: "babilonia.abzt.de"
  TUTOR_ROOT: ${{ github.repository }}
  TUTOR_PLUGINS_ROOT: $TUTOR_ROOT/plugins"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Generate tutor env
        run:  tutor config save

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: https://docker.io/
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build tutor openedx image
        run: tutor images build openedx --build-arg BUILDKIT_INLINE_CACHE=1 --docker-arg="--cache-from" --docker-arg="docker.io/abstract2tech/abstract-openedx:15.3.0" 
        
      - name: Psuh tutor openedx image
        run: tutor images push openedx
  
  deploy:
    needs: build

    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy tutor
        run: |
          ssh tutor@${{ env.SERVER_IP }} "cd /opt/tutor/config/ && git pull && tutor images pull openedx && tutor local restart"      
